fix = true
unsafe-fixes = true
line-length = 100
output-format = 'grouped'
target-version = 'py312'
exclude = ['examples/']

[format]
quote-style = 'single'

[lint]
select = ['B', 'C4', 'E', 'F']
ignore = ['B023']

[lint.pycodestyle]
max-line-length = 120
