"$schema" = 'https://starship.rs/config-schema.json'

format = """
[](color_user)\
$os$username$hostname\
[](bg:color_dir fg:color_user)\
$directory\
[](fg:color_dir bg:color_git)\
$git_branch$git_status\
[](fg:color_git bg:color_lang)\
$c$cpp$golang$java$kotlin$lua$nodejs$php$python$ruby$rust\
[](fg:color_lang bg:color_bg1)\
$docker_context\
[ ](fg:color_bg1)\
$line_break$character"""

right_format = """
[](color_bg1)\
$time\
[](fg:color_bg1 bg:color_bg0)\
$battery\
[ ](fg:color_bg0)\
"""

palette = 'gruvbox-dark'
# palette = 'tokyo-night'
# palette = 'catppuccin-mocha'

[palettes.gruvbox-dark]
color_fg0       = '#fbf1c7'
color_fg1       = '#fbf1c7'
color_bg0       = '#3c3836'
color_bg1       = '#665c54'
color_lang      = '#458588'
color_git       = '#689d6a'
color_user      = '#d65d0e'
color_dir       = '#d79921'

[palettes.tokyo-night]
color_fg0       = '#e3e5e5'
color_fg1       = '#769ff0'
color_bg0       = '#1d2230'
color_bg1       = '#212736'
color_lang      = '#212736'
color_git       = '#394260'
color_user      = '#769ff0'
color_dir       = '#769ff0'

[palettes.catppuccin-mocha]
color_fg0       = '#11111b'
color_fg1       = '#11111b'
color_bg0       = '#b4befe'
color_bg1       = '#74c7ec'
color_lang      = '#a6e3a1'
color_git       = '#f9e2af'
color_user      = '#f38ba8'
color_dir       = '#fab387'

[os]
disabled = false
style = "bg:color_user fg:color_fg1"

[os.symbols]
Alpine = ""
Amazon = ""
Arch = "󰣇"
Debian = "󰣚"
# EndeavourOS = " "
EndeavourOS = "󰣇"
Fedora = "󰣛"
Linux = "󰌽"
Macos = "󰀵"
Manjaro = ""
Mint = "󰣭"
Pop = ""
Redhat = "󱄛"
SUSE = ""
Ubuntu = "󰕈"
Windows = "󰍲"

[username]
show_always = true
style_user = "bg:color_user fg:color_fg0"
style_root = "bg:color_user fg:color_fg0"
format = '[ $user ]($style)'

[hostname]
ssh_only = true
format = '[$ssh_symbol$hostname]($style)'
style = "bg:color_user fg:color_fg1"
trim_at = '.companyname.com'
disabled = false

[directory]
style = "fg:color_fg1 bg:color_dir"
format = "[ $path ]($style)"
truncation_length = 3
truncation_symbol = "…/"

[directory.substitutions]
"Documents" = "󰈙 "
"Downloads" = " "
"Music" = "󰝚 "
"Pictures" = " "
"workspace" = "󰲋 "

[git_branch]
symbol = ""
style = "bg:color_git"
format = '[[ $symbol $branch ](fg:color_fg1 bg:color_git)]($style)'

[git_status]
style = "bg:color_git"
format = '[[($all_status$ahead_behind )](fg:color_fg1 bg:color_git)]($style)'

[docker_context]
symbol = ""
style = "bg:color_bg1"
format = '[[ $symbol( $context) ](fg:#83a598 bg:color_bg1)]($style)'

[time]
disabled = false
use_12hr = true
format = '[$time]($style)'
time_format = '%I:%M'
style = 'fg:color_fg0 bg:color_bg1'

[battery]
format = '[$symbol$percentage]($style)'

[[battery.display]]
style = 'fg:color_dir bg:color_bg0'
threshold = 80


# Languages
# ----------

[c]
symbol = " "
style = "bg:color_lang"
format = '[[ $symbol ](fg:color_fg1 bg:color_lang)]($style)'

# [cpp]
# symbol = " "
# style = "bg:color_lang"
# format = '[[ $symbol ](fg:color_fg1 bg:color_lang)]($style)'

[golang]
symbol = ""
style = "bg:color_lang"
format = '[[ $symbol ](fg:color_fg1 bg:color_lang)]($style)'

[java]
symbol = ""
style = "bg:color_lang"
format = '[[ $symbol ](fg:color_fg1 bg:color_lang)]($style)'

[kotlin]
symbol = ""
style = "bg:color_lang"
format = '[[ $symbol ](fg:color_fg1 bg:color_lang)]($style)'

[lua]
symbol = " "
style = "bg:color_lang"
format = '[[ $symbol ](fg:color_fg1 bg:color_lang)]($style)'

[nodejs]
symbol = ""
style = "bg:color_lang"
format = '[[ $symbol ](fg:color_fg1 bg:color_lang)]($style)'

[php]
symbol = ""
style = "bg:color_lang"
format = '[[ $symbol ](fg:color_fg1 bg:color_lang)]($style)'

[python]
symbol = ""
style = "bg:color_lang"
format = '[$symbol($version )(\($virtualenv\) )]($style)'
version_format = '$major.$minor'

[ruby]
symbol = " "
style = "bg:color_lang"
format = '[[ $symbol ](fg:color_fg1 bg:color_lang)]($style)'

[rust]
symbol = "󱘗 "
style = "bg:color_lang"
format = '[[ $symbol ](fg:color_fg1 bg:color_lang)]($style)'
