FROM fedora:43

# Create test-user with sudo privileges and no password
RUN dnf update -y \
    && useradd -m test-user \
    && echo "test-user ALL=(ALL) NOPASSWD:ALL" > /etc/sudoers.d/test-user \
    && chmod 0440 /etc/sudoers.d/test-user

# Install minimal packages needed for setup
COPY --chown=test-user:test-user scripts/install_bootstrap_packages.sh /home/test-user/dotfiles/scripts/
USER test-user
WORKDIR /home/test-user/dotfiles
ENV PATH="/home/test-user/.local/bin:${PATH}"
RUN scripts/install_bootstrap_packages.sh

# Run full install script when image runs
COPY --chown=test-user:test-user . /home/test-user/dotfiles
CMD ["just", "install"]
